### ISSUE TITLE
Add Custom Post type Plugin

### ISSUE THREAD

**Issue by edheltzel** [RainyDayMedia/RDMGumbyShell#2]
I'm thinking we should include a CPT plugin as required. This way when/if a customer decides to update or swap out their theme. They don't loose that info.

**Comment by Toddses** [comment]
How are you thinking this would be implemented?

**Comment by Toddses** [comment]
I guess my question here is really more of a refactoring issue. I built out the theme functions to easily be able to turn features on and off. But I think we're headed more down the path of using the shell as a parent theme, and building child themes off of that. I'll open another issue to discuss that.

**Comment by Toddses** [comment]
Going to close this one. The functions file includes

``` php
// Set up the custom post types, if there are any
// we build out our CPT using a custom plugin with the below function
if ( function_exists( 'theme_custom_post_types' ) ) {
    theme_custom_post_types();
}
```

So we can just add a custom CPT plugin and include a function `theme_custom_post_types()` to pull in the CPT.
